### PR TITLE
Refactored WoloxCallback, code cleanup and updated networking dependencies.

### PR DESCRIPTION
**Pull request by juanignaciomolina**
## Networking update

* **Refactored WoloxCallback:** There was garbage code ported from another project.
* **Updated networking dependencies:** Updated Retrofit and OkHTTP to the latest stable versions.

### CODE REVIEW

**Comment by juanignaciomolina** [comment]
@framundo 👍 good catch! Should we merge this now?

**Comment by framundo** [comment]
@juanignaciomolina We should ask the GC dev team to try this branch or the specific commit (	a13248c) and make sure it works before merging.

**Comment by alvarez-fabian** [comment]
I'm testing it. I'll let you know if it works.

**Comment by alvarez-fabian** [comment]
@juanignaciomolina It's working OK :+1:

**Comment by juanignaciomolina** [comment]
@framundo 👆 we should merge this now :)

**Pull request merged**
